### ISSUE TITLE
Widget for cell data usage on premiumsim.de / winsim.de / handyvertrag.de (Drillisch)

### ISSUE THREAD

**Issue by LordVoodoo** [dersvenhesse/awesome-scriptable#17]
Please add this scriptable widget to your list, it shows the used and total available cellular data for three brands of the Drillisch group.

https://github.com/BergenSoft/scriptable_premiumsim

**Comment by dersvenhesse** [comment]
Closed via https://github.com/dersvenhesse/awesome-scriptable/commit/414e7ac7ca7fc964cf929b2275d07409cbb2c9eb.
